# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip" # For Python projects
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
